enableImmutableInstalls: false

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-berry.cjs
